---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-0
  labels:
    pv: data-consul-0
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "consul-0"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-1
  labels:
    pv: data-consul-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "consul-1"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-2
  labels:
    pv: data-consul-2
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "consul-2"
    readOnly: false
---
